-- ============================================================
-- Vértice — schema PostgreSQL v2.0.0
--
-- Sucessor do schema SQLite. Mudanças relevantes vs SQLite:
--
--   * UUID nativo (em vez de TEXT) — comparações e indexação mais eficientes.
--   * JSONB (em vez de TEXT) — em todas as colunas que armazenam payloads
--     estruturados. Permite indexação GIN e queries `?`/`@>` nativas.
--   * BOOLEAN (em vez de INTEGER 0/1) — semântica clara, sem cast no app.
--   * TIMESTAMPTZ (em vez de TIMESTAMP/TEXT) — armazena timezone, evita
--     ambiguidades em logs/auditoria distribuídos.
--   * GENERATED BY DEFAULT AS IDENTITY (em vez de AUTOINCREMENT).
--   * IF NOT EXISTS em todos os CREATE TABLE/INDEX e em ALTER TABLE ADD
--     COLUMN — eliminando o ciclo PRAGMA table_info dos antigos migrations.
--
-- Convenção: índices por (created_at DESC) usam ordem reversa para alinhar
-- com a varredura típica "mais recente primeiro" das telas (auditoria,
-- presentations, finops).
-- ============================================================

-- Auth & RBAC
CREATE TABLE IF NOT EXISTS users (
    id              UUID PRIMARY KEY,
    username        TEXT NOT NULL UNIQUE,
    full_name       TEXT NOT NULL DEFAULT '',
    email           TEXT NOT NULL DEFAULT '',
    phone           TEXT NOT NULL DEFAULT '',
    department      TEXT NOT NULL DEFAULT '',
    title           TEXT NOT NULL DEFAULT '',
    hashed_password TEXT NOT NULL,
    salt            TEXT NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS roles (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS permissions (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id UUID    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id       INTEGER NOT NULL REFERENCES roles(id)       ON DELETE CASCADE,
    permission_id INTEGER NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

-- Module Registry
CREATE TABLE IF NOT EXISTS modules (
    id              UUID PRIMARY KEY,
    name            TEXT NOT NULL UNIQUE,
    endpoint_url    TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'active',
    config_params   JSONB,
    description     TEXT NOT NULL DEFAULT '',
    skill_path      TEXT,
    response_type   TEXT NOT NULL DEFAULT 'text',
    response_config JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- API Endpoints externos (configurados pelo admin para uso por módulos
-- response_type='api')
CREATE TABLE IF NOT EXISTS api_endpoints (
    id              UUID PRIMARY KEY,
    name            TEXT NOT NULL UNIQUE,
    description     TEXT NOT NULL DEFAULT '',
    url             TEXT NOT NULL,
    method          TEXT NOT NULL DEFAULT 'POST',
    headers         JSONB,
    timeout_seconds INTEGER NOT NULL DEFAULT 30,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_user TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Histórico de chamadas a APIs externas (auditoria + debug)
CREATE TABLE IF NOT EXISTS api_calls (
    id              UUID PRIMARY KEY,
    api_endpoint_id UUID NOT NULL REFERENCES api_endpoints(id),
    module_id       UUID,
    user_id         UUID,
    request_body    JSONB,
    response_status INTEGER,
    response_body   JSONB,
    duration_ms     DOUBLE PRECISION,
    error           TEXT,
    called_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_api_calls_endpoint
    ON api_calls(api_endpoint_id, called_at DESC);

-- Prompts (guardrail-system-guardrail)
CREATE TABLE IF NOT EXISTS prompts (
    id               UUID PRIMARY KEY,
    module_name      TEXT,                   -- legado (mantido para compat)
    module_names     JSONB,                  -- nova: lista de módulos
    name             TEXT NOT NULL,
    version          INTEGER NOT NULL,
    input_guardrail  TEXT,
    system_prompt    TEXT NOT NULL,
    output_guardrail TEXT,
    is_active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (name, version)
);
CREATE INDEX IF NOT EXISTS idx_prompts_name        ON prompts(name);
CREATE INDEX IF NOT EXISTS idx_prompts_module_name ON prompts(module_name);
-- GIN sobre JSONB permite procurar prompts cujo array contenha o módulo X.
CREATE INDEX IF NOT EXISTS idx_prompts_module_names ON prompts USING GIN (module_names);

-- ===== BKO Inteligente: casos (XLSX) + transcrições (JSON) =====
CREATE TABLE IF NOT EXISTS bko_cases (
    case_number     TEXT PRIMARY KEY,
    created_by      TEXT,
    owner           TEXT,
    phone           TEXT,
    opened_at       TIMESTAMPTZ,
    contract_msisdn TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_bko_cases_contract ON bko_cases(contract_msisdn);

CREATE TABLE IF NOT EXISTS transcripts (
    transaction_id      TEXT PRIMARY KEY,
    verint_nr_contrato  TEXT,
    transcription_text  TEXT,
    started_at          TIMESTAMPTZ,
    duration_s          DOUBLE PRECISION,
    segment             TEXT,
    msisdn              TEXT,
    ani                 TEXT,
    cpf                 TEXT,
    employee            TEXT,
    raw_json            JSONB,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_transcripts_nr_contrato
    ON transcripts(verint_nr_contrato);

-- ===== Rastreabilidade (Audit Trail) =====
-- Registra TODAS as ações: chamadas HTTP, execuções de módulo, mudanças de
-- configuração, uploads, etc.
CREATE TABLE IF NOT EXISTS audit_events (
    id          UUID PRIMARY KEY,
    ts          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_id     UUID,
    username    TEXT,
    category    TEXT NOT NULL,
    action      TEXT NOT NULL,
    target      TEXT,
    status_code INTEGER,
    duration_ms DOUBLE PRECISION,
    feature     TEXT,
    payload     JSONB,
    error       TEXT,
    ip          TEXT,
    user_agent  TEXT
);
CREATE INDEX IF NOT EXISTS idx_audit_ts       ON audit_events(ts DESC);
CREATE INDEX IF NOT EXISTS idx_audit_category ON audit_events(category, ts DESC);
CREATE INDEX IF NOT EXISTS idx_audit_user     ON audit_events(user_id, ts DESC);
CREATE INDEX IF NOT EXISTS idx_audit_feature  ON audit_events(feature, ts DESC);
-- Alta seletividade em busca por status >= 400 (filtro recorrente da página).
CREATE INDEX IF NOT EXISTS idx_audit_status_err
    ON audit_events(status_code, ts DESC) WHERE status_code >= 400;

-- ===== Galeria de Apresentações =====
CREATE TABLE IF NOT EXISTS presentations (
    id              UUID PRIMARY KEY,
    title           TEXT NOT NULL,
    subtitle        TEXT,
    feature         TEXT,
    case_number     TEXT,
    sections        JSONB NOT NULL,
    insights        JSONB,
    visuals         JSONB,
    chat_history    JSONB,
    created_by_user TEXT,
    created_by_id   UUID,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    cost_estimated  DOUBLE PRECISION NOT NULL DEFAULT 0,
    tokens_input    INTEGER NOT NULL DEFAULT 0,
    tokens_output   INTEGER NOT NULL DEFAULT 0,
    model_used      TEXT
);
CREATE INDEX IF NOT EXISTS idx_presentations_created ON presentations(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_presentations_user    ON presentations(created_by_id);
CREATE INDEX IF NOT EXISTS idx_presentations_feature ON presentations(feature);

-- Contracts (Radar Voz do Cliente)
CREATE TABLE IF NOT EXISTS contracts (
    contract_number TEXT PRIMARY KEY,
    call_id         TEXT,
    contact_id      TEXT,
    operator        TEXT,
    contact_at      TIMESTAMPTZ,
    segment         TEXT NOT NULL DEFAULT 'RESIDENCIAL',
    transcript      TEXT NOT NULL DEFAULT '',
    extra           JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_contracts_contact_at ON contracts(contact_at DESC);
CREATE INDEX IF NOT EXISTS idx_contracts_operator   ON contracts(operator);

-- Analysis Cards
CREATE TABLE IF NOT EXISTS analysis_cards (
    id              UUID PRIMARY KEY,
    contract_number TEXT NOT NULL REFERENCES contracts(contract_number) ON DELETE CASCADE,
    name            TEXT NOT NULL,
    output_type     TEXT NOT NULL,
    prompt_text     TEXT NOT NULL,
    expected_size   TEXT NOT NULL DEFAULT '',
    model_used      TEXT,
    result          TEXT,
    confidence      DOUBLE PRECISION,
    tokens_input    INTEGER NOT NULL DEFAULT 0,
    tokens_output   INTEGER NOT NULL DEFAULT 0,
    cost_estimated  DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_cards_contract ON analysis_cards(contract_number);

-- Churn taxonomy
CREATE TABLE IF NOT EXISTS churn_nodes (
    id          UUID PRIMARY KEY,
    label       TEXT NOT NULL,
    parent_id   UUID REFERENCES churn_nodes(id) ON DELETE CASCADE,
    depth       INTEGER NOT NULL DEFAULT 0,
    examples    JSONB,
    occurrences INTEGER NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_churn_parent ON churn_nodes(parent_id);

CREATE TABLE IF NOT EXISTS churn_classifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_number TEXT NOT NULL,
    path            JSONB NOT NULL,
    confidence      DOUBLE PRECISION,
    rationale       TEXT,
    classified_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_churn_class_contract
    ON churn_classifications(contract_number, classified_at DESC);

-- FinOps Ledger — dimensões de chargeback/showback modernas:
--   domain, product, agent, flow, prompt_id, integration, environment.
-- Latência (latency_ms) e storage (storage_bytes) são opcionais. Todas as
-- colunas começam nullable para gravações antigas continuarem válidas.
CREATE TABLE IF NOT EXISTS finops_ledger (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         UUID,
    module_id       UUID,
    model_name      TEXT,
    tokens_input    INTEGER NOT NULL DEFAULT 0,
    tokens_output   INTEGER NOT NULL DEFAULT 0,
    cost_estimated  DOUBLE PRECISION NOT NULL DEFAULT 0,
    context_tag     TEXT NOT NULL DEFAULT '',
    domain          TEXT,
    product         TEXT,
    agent           TEXT,
    flow            TEXT,
    prompt_id       TEXT,
    integration     TEXT,
    environment     TEXT NOT NULL DEFAULT 'production',
    latency_ms      DOUBLE PRECISION,
    storage_bytes   BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_finops_created     ON finops_ledger(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_finops_model       ON finops_ledger(model_name);
CREATE INDEX IF NOT EXISTS idx_finops_domain      ON finops_ledger(domain);
CREATE INDEX IF NOT EXISTS idx_finops_agent       ON finops_ledger(agent);
CREATE INDEX IF NOT EXISTS idx_finops_environment ON finops_ledger(environment);
-- Índice composto para a query do Cockpit (filtros típicos: 24h por modelo).
CREATE INDEX IF NOT EXISTS idx_finops_ts_model
    ON finops_ledger(created_at DESC, model_name);
-- Para chargeback por módulo (extrai prefixo de context_tag antes da '/')
-- via SPLIT_PART. Index parcial para acelerar GROUP BY agregações comuns.
CREATE INDEX IF NOT EXISTS idx_finops_context_tag ON finops_ledger(context_tag);

-- FinOps Budgets
CREATE TABLE IF NOT EXISTS finops_budgets (
    id                UUID PRIMARY KEY,
    name              TEXT NOT NULL,
    scope_type        TEXT NOT NULL,
    scope_value       TEXT,
    period            TEXT NOT NULL DEFAULT 'monthly',
    limit_brl         DOUBLE PRECISION NOT NULL,
    warning_threshold DOUBLE PRECISION NOT NULL DEFAULT 0.8,
    hard_stop         BOOLEAN NOT NULL DEFAULT FALSE,
    notes             TEXT,
    created_by        UUID,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_budgets_scope
    ON finops_budgets(scope_type, scope_value);

-- FinOps Model Policies
CREATE TABLE IF NOT EXISTS finops_model_policies (
    id                  UUID PRIMARY KEY,
    model_name          TEXT NOT NULL UNIQUE,
    risk_tier           TEXT NOT NULL DEFAULT 'medium',
    value_tier          TEXT NOT NULL DEFAULT 'medium',
    max_cost_per_call   DOUBLE PRECISION,
    max_tokens_per_call INTEGER,
    allowed_features    JSONB,
    rationale           TEXT,
    enabled             BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- FinOps Alerts
CREATE TABLE IF NOT EXISTS finops_alerts (
    id              UUID PRIMARY KEY,
    budget_id       UUID NOT NULL REFERENCES finops_budgets(id) ON DELETE CASCADE,
    severity        TEXT NOT NULL,
    cost_observed   DOUBLE PRECISION NOT NULL,
    limit_reference DOUBLE PRECISION NOT NULL,
    period_start    TIMESTAMPTZ,
    period_end      TIMESTAMPTZ,
    triggered_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at     TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_alerts_budget
    ON finops_alerts(budget_id, triggered_at DESC);

-- ===== Raio X Cliente =====
CREATE TABLE IF NOT EXISTS raiox_boards (
    id                  UUID PRIMARY KEY,
    name                TEXT NOT NULL,
    description         TEXT NOT NULL DEFAULT '',
    owner_id            UUID,
    is_shared           BOOLEAN NOT NULL DEFAULT TRUE,
    allowed_roles       JSONB,
    allowed_departments JSONB,
    layout_json         JSONB,
    filters_json        JSONB,
    cover_emoji         TEXT NOT NULL DEFAULT '🩻',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_raiox_boards_owner ON raiox_boards(owner_id);
-- Trilha do último editor — actor tracking simétrico a radar_card_visibility.
ALTER TABLE raiox_boards
    ADD COLUMN IF NOT EXISTS updated_by_id TEXT;
ALTER TABLE raiox_boards
    ADD COLUMN IF NOT EXISTS updated_by_username TEXT;

CREATE TABLE IF NOT EXISTS raiox_charts (
    id                 UUID PRIMARY KEY,
    board_id           UUID NOT NULL REFERENCES raiox_boards(id) ON DELETE CASCADE,
    title              TEXT,
    chart_type         TEXT NOT NULL,
    position_row       INTEGER NOT NULL DEFAULT 0,
    position_col       INTEGER NOT NULL DEFAULT 0,
    span_cols          INTEGER NOT NULL DEFAULT 1,
    span_rows          INTEGER NOT NULL DEFAULT 1,
    query_spec_json    JSONB NOT NULL,
    plotly_config_json JSONB,
    skill_path         TEXT,
    created_by_ai      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_raiox_charts_board ON raiox_charts(board_id);
ALTER TABLE raiox_charts
    ADD COLUMN IF NOT EXISTS updated_by_id TEXT;
ALTER TABLE raiox_charts
    ADD COLUMN IF NOT EXISTS updated_by_username TEXT;

CREATE TABLE IF NOT EXISTS raiox_analyses (
    id              UUID PRIMARY KEY,
    board_id        UUID NOT NULL REFERENCES raiox_boards(id) ON DELETE CASCADE,
    user_id         UUID,
    username        TEXT,
    charts_snapshot JSONB,
    per_chart_json  JSONB,
    synthesis_json  JSONB,
    totals_json     JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_raiox_analyses_board
    ON raiox_analyses(board_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_raiox_analyses_user
    ON raiox_analyses(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS raiox_relationships (
    id                UUID PRIMARY KEY,
    table_a           TEXT NOT NULL,
    column_a          TEXT NOT NULL,
    table_b           TEXT NOT NULL,
    column_b          TEXT NOT NULL,
    kind              TEXT NOT NULL DEFAULT 'one_to_many',
    confidence        DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    confirmed_by_user TEXT,
    confirmed_at      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (table_a, column_a, table_b, column_b)
);
CREATE INDEX IF NOT EXISTS idx_raiox_rel_a ON raiox_relationships(table_a);
CREATE INDEX IF NOT EXISTS idx_raiox_rel_b ON raiox_relationships(table_b);

-- ===== Radar Voz do Cliente — estado por usuário =====
-- user_id é TEXT (não UUID) intencionalmente: no legado SQLite a FK para
-- `users(id)` não era enforced (PRAGMA foreign_keys ficava off), e a
-- coluna acabou usada também como bucket opaco em fluxos de teste/dev.
-- Mantemos TEXT em PG por compat, sem FK — orphan rows são toleráveis.
-- state_json continua TEXT: o frontend envia/recebe a string crua de
-- localStorage, e o servidor não interpreta. JSONB exigiria parse cego no
-- caminho rápido — preferimos blob opaco aqui.
CREATE TABLE IF NOT EXISTS radar_user_state (
    user_id    TEXT PRIMARY KEY,
    state_json TEXT NOT NULL DEFAULT '[]',
    version    INTEGER NOT NULL DEFAULT 1,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- Preferências por-usuário do Radar (last case, last auto-run tx, last chat
-- case). Antes ficavam só em localStorage do browser — agora persistem cross-
-- device. Mantém o blob opaco; o servidor só armazena.
ALTER TABLE radar_user_state
    ADD COLUMN IF NOT EXISTS preferences JSONB NOT NULL DEFAULT '{}'::jsonb;

-- ===== Radar Voz do Cliente — visibilidade por card =====
-- owner_id/created_by_id como TEXT pelo mesmo motivo de `radar_user_state`
-- (FK não era enforced no SQLite). Mantém compat com fluxos que usam IDs
-- arbitrários sem FK.
CREATE TABLE IF NOT EXISTS radar_card_visibility (
    card_uid            TEXT PRIMARY KEY,
    owner_id            TEXT NOT NULL,
    owner_username      TEXT,
    created_by_id       TEXT,
    created_by_username TEXT,
    group_id            TEXT,
    group_title         TEXT,
    module_id           TEXT,
    module_name         TEXT,
    module_description  TEXT,
    visibility          TEXT NOT NULL DEFAULT 'private',
    previous_visibility TEXT,
    card_json           JSONB,
    feature             TEXT NOT NULL DEFAULT 'radar',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_radar_card_vis_owner
    ON radar_card_visibility(owner_id);
CREATE INDEX IF NOT EXISTS idx_radar_card_vis_visibility
    ON radar_card_visibility(visibility);

-- Trilha de auditoria do último change de visibility — quem mudou e quando.
-- Para bases já existentes (ADD COLUMN IF NOT EXISTS é idempotente em PG ≥ 9.6).
ALTER TABLE radar_card_visibility
    ADD COLUMN IF NOT EXISTS visibility_changed_by_id TEXT;
ALTER TABLE radar_card_visibility
    ADD COLUMN IF NOT EXISTS visibility_changed_by_username TEXT;
ALTER TABLE radar_card_visibility
    ADD COLUMN IF NOT EXISTS visibility_changed_at TIMESTAMPTZ;

-- Trilha de auditoria do último change_owner administrativo.
ALTER TABLE radar_card_visibility
    ADD COLUMN IF NOT EXISTS owner_changed_by_id TEXT;
ALTER TABLE radar_card_visibility
    ADD COLUMN IF NOT EXISTS owner_changed_by_username TEXT;
ALTER TABLE radar_card_visibility
    ADD COLUMN IF NOT EXISTS owner_changed_at TIMESTAMPTZ;

-- Departamento de quem tornou o card público (snapshot no momento do share).
-- Define a audiência: cards com `sharer_department = X` só ficam visíveis para
-- usuários cujo `users.department = X`. NULL = sem filtro de departamento
-- (sharer era root, com privilégio cross-dept).
-- Política completa:
--   * root          → pode compartilhar sem restrição; sharer_department = NULL
--   * admin         → pode compartilhar, MAS só se tem dept preenchido E o
--                     dono do card está no mesmo dept; sharer_department = dept do admin
--   * supervisor    → idem admin (mesmo dept)
--   * analista_n*   → não pode compartilhar
ALTER TABLE radar_card_visibility
    ADD COLUMN IF NOT EXISTS sharer_department TEXT;

-- Reset forçado: cards públicos pré-existentes voltam a `private` para que
-- usuários reapliquem a visibilidade sob a nova regra de departamento.
-- Idempotente — só atinge linhas em estado público, que após o UPDATE viram
-- privadas e não voltam a bater no WHERE. `previous_visibility` preserva o
-- valor anterior, permitindo que o usuário consulte qual era e re-aplique
-- manualmente.
UPDATE radar_card_visibility
   SET previous_visibility = visibility,
       visibility = 'private',
       updated_at = NOW()
 WHERE visibility IN ('public_lideranca', 'public_analista');

-- Artefatos efêmeros gerados por execuções de módulo (CSV, MD, JSON…).
-- TTL gerenciado no SELECT (filtra por created_at). GC opcional via DELETE
-- WHERE created_at < NOW() - INTERVAL '30 min' (chamado manualmente).
-- Substitui o dict in-memory anterior; agora persiste cross-worker e
-- sobrevive a restart.
CREATE TABLE IF NOT EXISTS artifacts (
    id          UUID PRIMARY KEY,
    filename    TEXT NOT NULL,
    mime_type   TEXT NOT NULL,
    content     BYTEA NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_artifacts_created_at
    ON artifacts(created_at DESC);

-- ===== Funcionalidades por Perfil — matriz (role × dept × feature) =====
-- Tela administrativa onde root configura quais funcionalidades cada perfil
-- pode acessar. Resolve gaps que page-level role gates não cobrem: por
-- exemplo, "analista_n3 do dept vendas vê /radar, do dept compras não vê".
--
-- Política de match (helper FeatureAccessService.can_access):
--   1. Sem nenhuma regra para (role, dept, feature) → ALLOW (default).
--      Migrate-safe: instalações existentes mantêm comportamento atual.
--   2. Regra com dept específico vence regra com dept='' (wildcard).
--   3. access=FALSE em qualquer regra match → DENY.
--   4. access=TRUE em regra match → ALLOW explícito.
--   5. ``root`` no set de roles do user → ALLOW (bypass total, supremo).
--
-- ``role`` armazena UM role por linha. Para um user com múltiplos roles,
-- o helper checa cada role separadamente — ALLOW se PELO MENOS UM permite.
-- ``department`` armazena dept exato OU '' (wildcard que casa qualquer).
-- ``feature_key`` é um slug curto ('radar', 'raiox' atualmente; futuro:
-- 'prompts', 'gallery', etc.).
CREATE TABLE IF NOT EXISTS feature_access (
    id                       UUID PRIMARY KEY,
    role                     TEXT NOT NULL,
    department               TEXT NOT NULL DEFAULT '',
    feature_key              TEXT NOT NULL,
    access                   BOOLEAN NOT NULL,
    created_by_id            TEXT,
    created_by_username      TEXT,
    updated_by_id            TEXT,
    updated_by_username      TEXT,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (role, department, feature_key)
);
CREATE INDEX IF NOT EXISTS idx_feature_access_lookup
    ON feature_access(role, feature_key);

-- Migration: força temperature=0 no módulo `radar` (Voz do Cliente).
-- Sem isso, com default 0.2 do router, a mesma transcrição gerava respostas
-- de tamanho/estrutura distintos entre auto-execute (troca de caso) e
-- re-executar manual — variação intrínseca de LLM com temp > 0. Como o
-- módulo é usado pra análise estruturada (intenção, justificativa), o
-- ganho de determinismo supera a perda de diversidade.
-- Operador `||` faz MERGE em JSONB (insere/atualiza apenas a key). Filtro
-- `NOT (... ? 'temperature')` torna a migration idempotente — só atinge
-- linhas sem o campo, preservando overrides manuais já feitos pelo admin.
UPDATE modules
   SET config_params = COALESCE(config_params, '{}'::jsonb) || '{"temperature": 0.0}'::jsonb
 WHERE name = 'radar'
   AND NOT (COALESCE(config_params, '{}'::jsonb) ? 'temperature');

-- Migration: renomeação da feature 'radar' → 'vozcliente' na matriz.
-- O módulo continua sendo o mesmo (rotas /radar, pasta templates/radar/,
-- código Python referenciando 'radar' como nome interno) — só a face
-- exposta na tela administrativa /access muda para o nome de produto.
-- Idempotente: re-execuções não fazem nada (WHERE só casa linhas com
-- a chave antiga).
UPDATE feature_access
   SET feature_key = 'vozcliente',
       updated_at = NOW()
 WHERE feature_key = 'radar';

-- ============================================================
-- Knowledge Base — documentos + chunks vetorizados (pgvector)
-- ============================================================
--
-- Stack: Docling (extração) + Azure OpenAI text-embedding-3-small (1536 dims)
-- + pgvector (busca semântica cosine). Tudo no Postgres — sem object storage
-- nem dependência externa. BYTEA armazena o arquivo original (cap 25MB no
-- adapter HTTP), markdown_extracted guarda o texto estruturado pelo Docling
-- e knowledge_chunks contém os trechos vetorizados usados em retrieval.
--
-- Política de visibilidade: somente root/admin gerenciam KBs. Módulos podem
-- referenciar uma KB via `modules.knowledge_base_id` (FK opcional, ON DELETE
-- SET NULL) — quando set, o fluxo de execução do módulo injeta os top-K
-- chunks recuperados como contexto no system prompt.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS knowledge_bases (
    id              UUID PRIMARY KEY,
    name            TEXT NOT NULL UNIQUE,
    description     TEXT NOT NULL DEFAULT '',
    -- Modelo de embedding usado. Trocar o modelo invalida todos os chunks
    -- (dimensões/espaço diferentes) — guarda aqui para detectar mismatch.
    embedding_model TEXT NOT NULL DEFAULT 'text-embedding-3-small',
    embedding_dims  INTEGER NOT NULL DEFAULT 1536,
    -- Parâmetros do chunker (alteráveis sem schema migration).
    chunk_size      INTEGER NOT NULL DEFAULT 800,       -- ~800 tokens por chunk
    chunk_overlap   INTEGER NOT NULL DEFAULT 80,        -- 10% de overlap
    created_by_id   TEXT,
    created_by_username TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_knowledge_bases_name ON knowledge_bases(name);

CREATE TABLE IF NOT EXISTS knowledge_documents (
    id                UUID PRIMARY KEY,
    knowledge_base_id UUID NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,
    filename          TEXT NOT NULL,
    mime_type         TEXT NOT NULL DEFAULT 'application/octet-stream',
    size_bytes        BIGINT NOT NULL DEFAULT 0,
    -- Conteúdo original. NULL após extração bem-sucedida se a KB descartar
    -- o raw (não default — mantemos para reprocessamento futuro).
    raw_content       BYTEA,
    -- Output do Docling: markdown estruturado + JSONB com tabelas/seções.
    markdown_extracted TEXT NOT NULL DEFAULT '',
    structure_json    JSONB,
    -- Pipeline: pending → processing → ready → failed
    status            TEXT NOT NULL DEFAULT 'pending',
    error             TEXT,
    chunks_count      INTEGER NOT NULL DEFAULT 0,
    -- Telemetria do pipeline assíncrono. `progress_message` recebe updates
    -- humanos a cada etapa ("extraindo Docling…", "5/12 chunks embedados…")
    -- para o usuário acompanhar na UI. `processing_started_at` mede o tempo
    -- entre kickoff e ready/failed.
    progress_message  TEXT,
    processing_started_at TIMESTAMPTZ,
    uploaded_by_id    TEXT,
    uploaded_by_username TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at      TIMESTAMPTZ
);
-- Migração para DBs já criados antes destas colunas existirem.
ALTER TABLE knowledge_documents
    ADD COLUMN IF NOT EXISTS progress_message TEXT,
    ADD COLUMN IF NOT EXISTS processing_started_at TIMESTAMPTZ;
CREATE INDEX IF NOT EXISTS idx_knowledge_documents_kb
    ON knowledge_documents(knowledge_base_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_knowledge_documents_status
    ON knowledge_documents(status) WHERE status IN ('pending', 'processing');

CREATE TABLE IF NOT EXISTS knowledge_chunks (
    id                UUID PRIMARY KEY,
    knowledge_base_id UUID NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,
    document_id       UUID NOT NULL REFERENCES knowledge_documents(id) ON DELETE CASCADE,
    chunk_index       INTEGER NOT NULL,
    content           TEXT NOT NULL,
    -- Metadados úteis para retrieval contextual (headings da seção, página, etc).
    metadata          JSONB NOT NULL DEFAULT '{}'::jsonb,
    embedding         vector(1536),
    tokens_estimated  INTEGER NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- Lookup do chunk por documento (para listagem/inspeção).
CREATE INDEX IF NOT EXISTS idx_knowledge_chunks_doc
    ON knowledge_chunks(document_id, chunk_index);
-- Index ANN para busca vetorial. IVFFlat com cosine distance é o padrão
-- recomendado pelo pgvector para corpora < 1M chunks (caso típico aqui).
-- `lists` deve ser ajustado conforme volume: regra-de-bolso = sqrt(N).
-- Para KBs pequenas (<1k chunks), o planner pode escolher seq scan — sem
-- problema, o índice serve quando a KB cresce.
CREATE INDEX IF NOT EXISTS idx_knowledge_chunks_embedding
    ON knowledge_chunks USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);

-- FK opcional do módulo para uma KB. ON DELETE SET NULL: apagar a KB não
-- apaga o módulo, só desassocia. Idempotente para upgrades de instalações
-- existentes.
ALTER TABLE modules
    ADD COLUMN IF NOT EXISTS knowledge_base_id UUID
    REFERENCES knowledge_bases(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_modules_knowledge_base
    ON modules(knowledge_base_id) WHERE knowledge_base_id IS NOT NULL;

-- Failsafe inbox
CREATE TABLE IF NOT EXISTS failsafe_actions (
    id           UUID PRIMARY KEY,
    module_name  TEXT NOT NULL,
    description  TEXT NOT NULL,
    payload      JSONB,
    confidence   DOUBLE PRECISION,
    status       TEXT NOT NULL DEFAULT 'pending',
    requested_by UUID,
    decided_by   UUID,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_failsafe_status ON failsafe_actions(status);
